// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuzefzvjufahiqnijbwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1emVmenZqdWZhaGlxbmlqYnd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDMxODIsImV4cCI6MjA2OTYxOTE4Mn0.qgrxT6otEF1Hh5Y5LIfePLus54uqmj4733mGwtiOvNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);